export const RECORD_USERINFO = 'RECORD_USERINFO'
export const GET_USERINFO = 'GET_USERINFO'
export const OUT_LOGIN = 'OUT_LOGIN'
export const RETSET_NAME = 'RETSET_NAME'
export const SAVE_AVANDER = 'SAVE_AVANDER'
export const SAVE_ADDDETAIL = 'SAVE_ADDDETAIL'
export const SAVE_ADDRESS = 'SAVE_ADDRESS'
export const SAVE_QUESTION = 'SAVE_QUESTION'
export const ADD_ADDRESS = 'ADD_ADDRESS'
export const BUY_CART = 'BUY_CART'
export const ADD_RESS = 'ADD_RESS'

export const CLEAR_ORDER = 'CLEAR_ORDER'
export const GET_PLACE_ORDER = 'GET_PLACE_ORDER'
export const PLACE_ORDER = 'PLACE_ORDER'
export const QUENCE_END = 'QUENCE_END'
export const GET_QUENCE = 'GET_QUENCE'